### PR TITLE
2 notebooks to analyse metadata from bechdeltest.com and IMDB

### PR DESCRIPTION
**Pull request by gefleury**
- Investigate correlations between Bechdel test results and the director gender (over years)
- Investigate correlations between Bechdel test results and most frequently used words in movie titles/overviews

### CODE REVIEW

**Comment by TheoLvs** [comment]
Perfect

**Review by TheoLvs — COMMENTED** [review]
Perfect

**Review by TheoLvs — COMMENTED** [review]
Perfect

**Comment by gefleury** [comment]
I close this pull request and add the two notebooks on a new `analysis` branch

**Pull request closed without merging**
